version: 1
formatters:
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "line": "%(lineno)s", "message": "%(message)s"}'
    datefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: LOG_FILE_PATH
    mode: w
    maxBytes: 1048576
    backupCount: 5

root:
  level: DEBUG
  handlers: [file]
